config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do 

  	resources :comments
  end
  root "posts#index"

  get '/about', to: 'about_page#about'

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/about_page_controller.rb
class AboutPageController < ApplicationController
	def about

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post=Post.find(params[:post_id])
		if user_signed_in?
			@comment=@post.comments.create(params[:comment].permit(:name,:body).merge(user:current_user.id))
			redirect_to post_path(@post)
		else 
			@comment=@post.comments.create(params[:comment].permit(:name,:body).merge(user:0))
			redirect_to post_path(@post),
		notice: "Only Owner Who Can add The Post"
		end

	end
	def edit
		@post=Post.find(params[:post_id])
		@comment=@post.comments.find(params[:id])
	end
	
	def update
			if @comment.user == current_user.id
				if @comment.update(params[:comment].permit(:title, :body).merge(user_id: current_user.id))
					redirect_to @post
				else
					render 'edit'
				end
		else 
			if user_signed_in?
				redirect_to @post,
     			notice: "Only Owner Who Can Edit The Post"
			else 
				redirect_to new_user_session_path
			end
		end
	end
	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		if @comment.user == current_user.id
			@comment.destroy
			redirect_to post_path(@post)
		else 
			if user_signed_in?
				redirect_to @post,
     			notice: "Only Owner Who Can Delete The Comment"
			else 
				redirect_to new_user_session_path
			end
		end

	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts=Post.all.order("created_at DESC")
	end
	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		print (@user)
		if @post.save
			redirect_to @post
		else 
			render 'new'
		end
	end
	def new
		@post=Post.new
	end
	def edit
	end
	def show
		@user = User.find(@post.user_id)
	end
	def update
			if @post.user_id == current_user.id
				if @post.update(params[:post].permit(:title, :body))
					redirect_to @post
				else
					render 'edit'
				end
		else 
			if user_signed_in?
				redirect_to @post,
     			notice: "Only Owner Who Can Edit The Post"
			else 
				redirect_to new_user_session_path
			end
		end
	end
	def destroy
		@post = Post.find(params[:id])
		if @post.user_id == current_user.id
			@post.destroy
			redirect_to posts_path
		else 
			if user_signed_in?
				redirect_to root_path,
     			notice: "Only Owner Who Can Delete The Post"
			else 
				redirect_to new_user_session_path
			end
		end
	end


	 private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/about_page_helper.rb
module AboutPageHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about_page/about.html.erb
<div id="page_wrapper">
	<div id="profile_image"><%= image_tag "logo.jpg" %></div>
	<div id="content"><br /><br />This is a simple Blog which allow users to add a post and comments. <br \> The loged-in user onle can edit,delete,add new posts. As well, only the owner of a post or a comment who can delete the post,comment. How Ever, the other can show posts and add comments.
	This is my first app using rails *_* </div>

</div>

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>
	<% if user_signed_in? %>
	<span class="button"><%= link_to 'Delete',[comment.post,comment], 
		method: :delete,
		data: {confirm: 'Are You Sure ??'}%> </span><span class="button"><%= link_to 'Edit',edit_post_comment_path(@post,comment.id)%></span>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <br>
 
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Comment</h1>
	<%= render 'form' %>
</div>

app/views/comments/index.html.erb
<% @comments.each do |comment|%>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to comment.name,root_path %>
		</h2>
		<p class="date">
			comment.body
		</p>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

    <<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	 <div id="sidebar">
  	<div id="logo">
  		<%= link_to root_path do %>
  		<%= image_tag "logo.jpg" %>
  		<% end %>
  	</div>
  	<div>
  		<ul>
  			<li class="cat">Website</li>
  			<li> <%= link_to "Blog", root_path %></li>
  			<li> <%= link_to "About",about_path %></li>
  		</ul>
  		<ul>
  			<li class="cat">Social</li>
  			<li><a href="https://www.twitter.com">Twitter</a></li>
  			<li><a href="https://www.facebook.com">Faceook</a></li>
  			<li><a href="https://www.yahoo.com">Yahoo</a></li>
  			<li><a href="https://www.gmail.com">Gamail</a></li>
  		</ul>
  		<p class="copy">&copy; March 11 2018 Khloud Ouda</p>
  	</div>
  	
  </div>
  <div id="main_content">
  	<div id="header">
        <% if current_page?(root_path) %>
						<p><%= link_to 'All Posts',posts_path %></p>
        <% elsif current_page?(about_path) %>
            <p>About</p>
        <% else %>
         <p> <%= link_to 'Back To All Posts', root_path %></p> 
          <% end %>
          <div class="buttons">
          <% if user_signed_in? %>
      					<p class="button">
      						<%= link_to 'New Post',new_post_path %>
      					</p>
      					<p class="button"><%= link_to 'Log Out', destroy_user_session_path,method: :delete%></p></p>
            <% else %>
                <p class="button"><%= link_to 'Log In', user_session_path %></p>
            <% end %>
      		</div>
    
  	</div>
  	<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
	<% end %>
    <%= yield %>
  </div>
  
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f|%> 
	  <% if @post.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

	      <ul>
	      <% @post.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
  	<% end %>

		<p>
			<%= f.label :title %><br />
			<%= f.text_field :title %>
		</p>
		<p>
			<%= f.label :body %> <br />
			<%= f.text_area:body %>
		</p>
		<p style="display:none">
			<%= f.label :userid %> <br />
			<%= f.text_field:user_id, id: :post_user_id %>
		</p>
		<p> 
			<%= f.submit %>
				
		</p>
	<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<p><%= notice %></p>
<% @posts.each do |post|%>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title,post %>
		</h2>
		<p class="date">
			<%= post.created_at.strftime("%B,%d,%Y") %>
		</p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	
	<h1>New Post</h1>
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	
	<h1 class="title">
		<%= @post.title %>
	</h1>
	<p class="date">
		submitted <%= time_ago_in_words(@post.created_at) %> ago
		 <% if user_signed_in? %>
		 	 | <%= link_to "Edit", edit_post_path(@post) %> | <%= link_to "Delete", post_path(@post), method: :delete,data:{confirm:'Are you sure you would like to delete it?'}%>
		 <% end %>
	</p>
	<p class="body">
		<%= @post.body %>
	</p>
	<p class="body">Created By: <%= @user.name %></p>
	<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>

		<h3>Add a comment</h3>
		<%= render 'comments/form' %>
	</div>
</div>